# 1. Import bibliotecas

In [1]:
import pandas as pd
import numpy as np

# 2 Leitura dos dados

## Fato

In [20]:
df_campeonato = pd.read_csv('campeonato-brasileiro-full.csv')
df_campeonato.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
0,1,1,29/3/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ
1,2,1,29/3/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS
2,3,1,30/3/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR
3,4,1,30/3/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA
4,5,1,30/3/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP

## Estatisticas da partida

In [4]:
df_estatisticas = pd.read_csv('campeonato-brasileiro-estatisticas-full.csv')
df_estatisticas.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0

## Cartões na partida

In [5]:
df_cartoes = pd.read_csv('campeonato-brasileiro-cartoes.csv')
df_cartoes.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
1,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72
2,4608,1,Vitoria,Amarelo,Marcelo Machado dos Santos,29.0,NaN,86
3,4608,1,Vitoria,Amarelo,Mansur,NaN,Zagueiro,10
4,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44

## Golds da partida

In [6]:
df_gols = pd.read_csv('campeonato-brasileiro-gols.csv')
df_gols.head()

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Fred,45,Penalty
1,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
2,4607,1,Fluminense,Rafael Sóbis,31,NaN
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4611,1,Sao Paulo,Antônio Carlos dos Santos Aguiar,13,NaN

# 3 Transformações

In [21]:
## Vencedor mandante ou visitante
condicoes = [(df_campeonato['vencedor']==df_campeonato['mandante']),\
             (df_campeonato['vencedor']==df_campeonato['visitante']),\
             (df_campeonato['vencedor']=='-')]

resultado_condicoes = ['mandante','visitante','empate']
df_campeonato['vencedor_mandante_visitante'] = np.select(condicoes,resultado_condicoes,default=np.nan)

df_campeonato.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,vencedor_mandante_visitante
0,1,1,29/3/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,mandante
1,2,1,29/3/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,mandante
2,3,1,30/3/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,empate
3,4,1,30/3/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,empate
4,5,1,30/3/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,empate

In [22]:
## Diferença de gols entre os clubes na partida
df_campeonato['diff_gols'] = abs(df_campeonato['mandante_Placar']-df_campeonato['visitante_Placar'])
df_campeonato.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,vencedor_mandante_visitante,diff_gols
0,1,1,29/3/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,mandante,2
1,2,1,29/3/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,mandante,2
2,3,1,30/3/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,empate,0
3,4,1,30/3/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,empate,0
4,5,1,30/3/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,empate,0

# 4 Perguntas

In [12]:
## Cada ano os times mudam
## Os times demoram se entrozar, quais times vencem mais após esse tempo de entrozamento? Quanto tempo até se entrozarem e obter resultados consistentes?
## As vitorias favorecem mais os mandantes ou os visitantes? - por hora, bimestre do ano,
## Como as vitorias favorecem mais quem abriu o placar? o time que abriu placar tem mais chances de vitorias?
## Times que abriram o placar e tomaram o empate tem mais chances de vitorias?
## Quais formações funcionam melhor contra qual outra formação? Olhar para vitórias e a diferença de gols na partida
## Nas mesmas condições de placar no momento do gol contra, o time que fez gol contra tem vantagem sobre quem nao fez? qual taxa de vitoria
## Há correlação entre numeros de faltas dos jogos, numero de penaltys do jogo e cartoes do jogo vs combinação das formações entre os times? quais formações mais favorecem o antijogo - anti-espetáculo
## Há correlação entre numeros de chutes no alvo no jogo vs combinação das formações entre os times? quais formações mais favorecem os chutes no alvo - favorece espetáculo
## Há correlação entre diff posse_de_bola do entre os times do jogo vs combinação das formações entre os times? quais formações mais favorecem o equilibrio no jogo - favorece espetáculo
## Há correlação entre numero de gols dos times do jogo vs combinação das formações entre os times? quais formações mais favorecem a qtde de gols no jogo - favorece espetáculo


##Avaliacao psicologica do time - fator psicológico

##cenario 1: empatados no momento da ocorrencia
##cenario 2: perdendo no momento da ocorrencia
##cenario 3: ganhando no momento da ocorrencia
##cenario especial: ganhando por 1 gol no momento da ocorrencia e cede empate por 1 gol contra ou penalty

## Partidas com gol contra: volume cenario 1 cenario 2 e cenario 3, cenario especial -->> tx de vitoria em cada cenario (quebrar por ocorrencia no primeiro ou segundo tempo - tmpo para se recuperar psicologicamente)
## Partidas com penalty: volume cenario 1 cenario 2 e cenario 3, cenario especial -->> tx de vitoria em cada cenario (quebrar por ocorrencia no primeiro ou segundo tempo - tmpo para se recuperar psicologicamente)
## Times que tomam amarelo: volume cenario 1 cenario 2 e cenario 3 -->> tx de vitoria em cada cenario (quebrar por posicao do cara q tomou cartao)
## Times que tomam vermelho: volume cenario 1 cenario 2 e cenario 3  -->> tx de vitoria em cada cenario (quebrar por posicao do cara q tomou cartao)


## Avaliação fisica do time - fator cansaço


##Tempo entre o jogo e o ultimo jogo.

In [14]:
df_estatisticas.tail()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
16045,8023,38,Atletico-MG,17,7,41%,351,82%,19,6,0,0,4
16046,8024,38,Internacional,15,8,48%,287,77%,13,2,0,1,6
16047,8024,38,Palmeiras,11,2,52%,306,82%,17,3,0,2,5
16048,8025,38,Goias,6,2,35%,330,80%,12,2,0,1,3
16049,8025,38,Sao Paulo,13,7,65%,591,90%,14,1,0,0,4